<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Sun Mar 07 20:56:58 WET 2021 -->

<!DOCTYPE personas [
	<!ELEMENT personas (persona+)>
	<!ELEMENT persona (nombre, apellidos, nacimiento?, direccion*, (varon | mujer))>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT apellidos (#PCDATA)>
	<!ELEMENT nacimiento EMPTY>
	<!ELEMENT direccion (calle, poblacion, provincia, codigo_postal?)>
	<!ELEMENT calle (#PCDATA)>
	<!ELEMENT poblacion (#PCDATA)>
	<!ELEMENT provincia (#PCDATA)>
	<!ELEMENT codigo_postal (#PCDATA)>
	<!ELEMENT varon EMPTY>
	<!ELEMENT mujer EMPTY>
	<!ATTLIST nacimiento dia CDATA #REQUIRED
				mes CDATA #REQUIRED
				anio CDATA #REQUIRED>
]>

<personas>
	<persona>
		<nombre>Jose Pedro</nombre>
		<apellidos>Balmaceda Pascal</apellidos>
		<nacimiento dia="2" mes="4" anio="1970"></nacimiento>
		<direccion>
			<calle>Calle Victoria</calle>
			<poblacion>La Orotava</poblacion>
			<provincia>Santa Cruz de Tenerife</provincia>
		</direccion>
		<varon></varon>
	</persona>
</personas>
