=== GersanCabo/gersanCaboLND/t7/14.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XSD document created with EditiX XML Editor (http://www.editix.com) at Tue Mar 23 13:56:03 WET 2021 -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.misitio.com" xmlns="http://www.misitio.com" 
elementFormDefault="qualified">

	<xs:element name="clinica">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="paciente" type="tipoPaciente" maxOccurs="500"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="tipoPersona">
		<xs:sequence>
			<xs:element name="nombre"/>
			<xs:element name="apellido"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="tipoPaciente">
		<xs:complexContent>
			<xs:extension base="tipoPersona">
				<xs:sequence>
					<xs:element name="visitante" type="tipoPersona" minOccurs="0" maxOccurs="2"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

</xs:schema>

=== GersanCabo/gersanCaboLND/t7/14.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Tue Mar 23 13:55:31 WET 2021 -->

<clinica xmlns="http://www.misitio.com" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.misitio.com 14.xsd">
	<paciente>
		<nombre>Luis</nombre>
		<apellido>Trujillo</apellido>
		<visitante>
			<nombre>Maria</nombre>
			<apellido>Li</apellido>
		</visitante>
	</paciente>
	<paciente>
		<nombre>Lola</nombre>
		<apellido>Flores</apellido>
		<visitante>
			<nombre>Mariano</nombre>
			<apellido>Perez</apellido>
		</visitante>
		<visitante>
			<nombre>Nino</nombre>
			<apellido>Vargas</apellido>
		</visitante>
	</paciente>
		<paciente>
		<nombre>Wanda</nombre>
		<apellido>Maximoff</apellido>
	</paciente>
</clinica>
