=== GersanCabo/gersanCaboLND/t7/final.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XSD document created with EditiX XML Editor (http://www.editix.com) at Tue Mar 23 15:41:34 WET 2021 -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.misitio.com" xmlns="http://www.misitio.com" 
elementFormDefault="qualified">

	<xs:element name="clinicaVeterinaria" type="tipoClinica"/>
	
	<xs:complexType name="tipoClinica">
			<xs:sequence>
				<xs:element name="cliente" type="tipoCliente" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="codigo" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="tipoCliente">
			<xs:sequence>
				<xs:element name="nombre" type="xs:string"/>
				<xs:element name="apellido" type="xs:string" minOccurs="0"/>
				<xs:element name="animal" type="tipoAnimal" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="tipoAnimal">
		<xs:choice>
			<xs:element name="perro" type="tipoEspecie"/>
			<xs:element name="gato" type="tipoEspecie"/>
			<xs:element name="reptil" type="tipoEspecie"/>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="tipoEspecie">
		<xs:sequence>
			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="edad" type="tipoEdadAnimal"/>
			<xs:element name="raza" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="sexo" type="tipoSexo" default="M"/>
	</xs:complexType>
	
	<xs:simpleType name="tipoEdadAnimal">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="15"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="tipoSexo">
		<xs:restriction base="xs:string">
			<xs:enumeration value="H"/>
			<xs:enumeration value="M"/>
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== GersanCabo/gersanCaboLND/t7/final.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Tue Mar 23 15:41:48 WET 2021 -->

<clinicaVeterinaria xmlns="http://www.misitio.com" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.misitio.com final.xsd" codigo="A0001">
	<cliente>
		<nombre>Alfredo</nombre>
		<apellido>Exposito</apellido>
		<animal>
			<perro sexo="H">
				<nombre>Firulais</nombre>
				<edad>9</edad>
				<raza>Labrador</raza>
			</perro>
		</animal>
	</cliente>
	<cliente>
		<nombre>Rosa</nombre>
		<apellido>Rodriguez</apellido>
		<animal>
			<gato>
				<nombre>Michi</nombre>
				<edad>3</edad>
				<raza>Egipcio</raza>
			</gato>
		</animal>
	</cliente>
	<cliente>
		<nombre>Pepe</nombre>
		<apellido>Boukkadour</apellido>
		<animal>
			<reptil sexo="M">
				<nombre>Ratatata</nombre>
				<edad>14</edad>
				<raza>Pit√≥n Real</raza>
			</reptil>
		</animal>
	</cliente>
</clinicaVeterinaria>
